//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLS.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Id { get; set; }
        public Nullable<int> BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public string ReaderName { get; set; }
        public int BorrowID { get; set; }
        public decimal FineMoney { get; set; }
        public Nullable<int> OverTime { get; set; }
        public Nullable<System.DateTime> FineDate { get; set; }
        public string IsPay { get; set; }
    
        public virtual Borrow Borrow { get; set; }
    }
}
